### ISSUE TITLE
Alien Trades shows barrier instead of empty

### ISSUE THREAD

**Issue by LegendaryTot** [gisellevonbingen/Minecraft-BossTools-Addon#10]
### Minecraft Version

1.18.1

### Forge Version

39.0.9

### Space-BossTools or Beyond Earth Version

1.18.1-5.9c

### Addon Mod Version (This Mod)

1.18.1-1.2

### The details

Alien Trades shows a barrier for some reason (i guess meaning item not needed)... Could that be changed to be empty like JER Villager Trades does it? 

![image](https://user-images.githubusercontent.com/96359623/147622359-57bbf6d3-cbef-4602-ba30-9ad452e27069.png)

**Comment by gisellevonbingen** [comment]
Yes, it meaning 'no needed'

If there is a mix of 1 and 2 items required for the same level,
It doesn't show up properly in the trade list (structural problem in jei, jer)

For example, if villager has the following trade list at the same level,
1. Diamond x1 => Emerald x1
1. Diamond x2 + Bread x1 => Emerald x2

JER shows as below
1. Diamond x1 + Bread x1 => Emerald x1
1. Diamond x2 + Bread x1 => Emerald x2

For this reason, i added a barrier to show the exact required item.
Then how about set barrier's displayname as "Not needed"?

And i can don't show barrier when all trades don't need second item in same level

**Comment by gisellevonbingen** [comment]
i will patch to like below

mostly
![image](https://user-images.githubusercontent.com/44163945/147650497-f14afc60-cb90-4f2f-a89b-50191983e584.png)

min in same level 1 items and 2 items trades
![image](https://user-images.githubusercontent.com/44163945/147650505-245d0c30-fc60-4070-a14c-ae9f4d9d6b06.png)

**Comment by LegendaryTot** [comment]
Ah I see. I didn't realize there was an issue with overlapping trades at same level for JER. Yeah maybe renaming the barrier to "Not Needed" might be less confusing (I saw it and was like how do I get a barrier).

**Comment by gisellevonbingen** [comment]
yh, good idea

**Comment by gisellevonbingen** [comment]
it done (a7c5c1c717cdafec7aca690815434250a448c711)
thanks for your attention
![image](https://user-images.githubusercontent.com/44163945/147744757-3816d012-5fac-4508-884a-9a558dbe1e26.png)
