### ISSUE TITLE
[1.18.1] Add Point of Interest to Alien Trades

### ISSUE THREAD

**Issue by LegendaryTot** [gisellevonbingen/Minecraft-BossTools-Addon#11]
### Minecraft Version

1.18.1

### Forge Version

39.0.9

### Space-BossTools or Beyond Earth Version

1.18.1-5.9c

### Addon Mod Version (This Mod)

1.18.1-1.2

### The details

JER Villager Trades also adds Point of Interest, which shows the required block for the villager profession. Could Alien Trades also add that too (or just integrate with JER)?

![image](https://user-images.githubusercontent.com/96359623/147622359-57bbf6d3-cbef-4602-ba30-9ad452e27069.png)

**Comment by gisellevonbingen** [comment]
ok i will check, alien has poi block

**Comment by gisellevonbingen** [comment]
it added
![image](https://user-images.githubusercontent.com/44163945/147651056-470c0964-da7a-4a9c-8ce2-b91974a74ab7.png)
