### ISSUE TITLE
Overworld like the moon? Oxygen lack ! 

### ISSUE THREAD

**Issue by alessandriLuca** [gisellevonbingen/Minecraft-BossTools-Addon#131]
### The details

Hi, i was thinking if you could add a feature activable via config or datapack that transform the overworld removing the oxygen. And maybe even change the sky, making the overworld looks like the outlands in world of warcraft! 
THanks!

**Comment by gisellevonbingen** [comment]
Oxygen lack, I'd love this idea.
But when addon implement this, there are some structural difficulties.

Suggest this to Beyond-Earth discord or Github first.
* https://discord.gg/Xb2nPmN
* https://github.com/MrScautHD/Beyond-Earth/issues

I will review again when If Beyond-Earth dev says no
