### ISSUE TITLE
Space Insulation upgrade/enchantment

### ISSUE THREAD

**Issue by Lgmrszd** [gisellevonbingen/Minecraft-BossTools-Addon#135]
### The details

Hello, I have played with this mod, it is great.
However, there is one thing that bothers me.
In order to survive in Space, you need entire Space Suit.

But with this mod you only need helmet with "Space Breathing" Enchantment.

![image](https://user-images.githubusercontent.com/16291541/208810147-1605f063-b7aa-4313-9aad-007c1c72d2ca.png)
*It doesn't even cover my face. Silly!*
 
I suggest adding something like "Space Insulation" enchantment (and also upgrades) that you need to add to other armor pieces.
With that, only when you have Helmet with Space Breathing and all three other armor pieces with Space Insulation, you would be able to survive in Space! :)

**Comment by gisellevonbingen** [comment]
Enchantment can be call 'magic'.
I'm imagine that enchantment is cover me with invisible oxygen aura.

Indeed, I'm worry about need more level in every time enchant.
So, i would added least enchantment as possible as.

Instead, how about change to that enchantment need equip all parts of equipment for operation?

**Comment by Lgmrszd** [comment]
That makes sense, and suggestion to check if other armor pieces are present sounds good. Also, could check if the Armor pieces are Iron or better (not Leather).
If you have time for this and you want to, having both options (with configuration: "require all armor to have Space Insulation") would be really cool!
But if you don't wanna do this I could try to implement this and send a Pull Request if that is okay.

Also since it's all related to "breathing", I have a suggestion for the recipes and another feature to request, but I'll make a separate issue for that.

**Comment by gisellevonbingen** [comment]
umm, leather armor have 'minecraft:freeze_immune_wearables'.
I think don't need armor material  be metal.

Config options is good idea. (require all armors to have Space Insulation)
Default value would be `false`.
Because maybe someone is on moon with only SpaceBreathing enchanted helmet.
i want they don't die on moon.

But,  It will be changed to `true` when Beyond Earth relesased version of 1.19.2.

**Comment by Lgmrszd** [comment]
This tag used to determine if armor prevents freezing in Powdered Snow. Space Suit doesn't have that tag, so I don't think it's related. I suggested to check for Iron Armor or better because Space Suit is made from Iron and Wool

My idea was that even though Enchantments are magic, they can't protect other body parts. Also, by this logic, other items like Mekanism Upgrades and PneumaticCraft Upgrades are not magic, so if player has only helmet without any armor then it can't protect.

I could also suggest that for your other addon, which is for Ad Astra! mod, if you need then I will open an issue in the repository of this addon.

**Comment by gisellevonbingen** [comment]
But I think that tag is meaning can resist cold.

In other side, Any method for compare armor material tiers?
And If I have to compare materials tier, Problem is how to support more armors added from other mods.
Protection is only?

Yes, I agree to Mekanism and PNC upgrades are should be too.

It is ok, Create at Ad-Astra Addon.

**Comment by Lgmrszd** [comment]
Yeah, that tag means that, but it's mostly used by Vanilla, and only Leather armor has this tag. I am sure that Leather Armor is far worse than Diamond for space travels x)

I don't know if there's method for comparing armor tiers, I just thought that Leather armor shouldn't work in outer space. I guess you can compare Armor defense points to be as good as Iron.

**Comment by gisellevonbingen** [comment]
I was work on 1.16.5 first.
If config is enabled, Player should be equip all parts armor to fit each features.
If there is no problem in implementation, I will port it to 1.18.2 soon.

You can test with this file, if you has interest. (Need change extension to `.jar`)
[Space-BossTools_Giselle_Addon-1.16.5-1.22.zip](https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/files/10279287/Space-BossTools_Giselle_Addon-1.16.5-1.22.zip)

**Comment by gisellevonbingen** [comment]
ok, i released new version added all features.
Can you test it?
https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/4240402

**Comment by Lgmrszd** [comment]
Thanks, I'll test it soon!

**Comment by Lgmrszd** [comment]
Tested, works as intended, thank you!
I only have question about two config options for enchantments:
There's two config options
- Enchant Least Iron
- Work Full Parts Least Iron
If you have second one enabled, then even if you disable first one you still need enchant at least Iron Armor... So it makes no sense.

**Comment by gisellevonbingen** [comment]
I think too.
Would it be better to combine their?

**Comment by Lgmrszd** [comment]
What about second option being just "Require full armor set"?
So it would be two options:
- Require Least Iron
- Require Full Armor Set

If only 1 is active, you can only enchant Iron or better
If only 2 is active, you can enchant Leather or other armor worse than Iron, but you need to have full armor
If 1 and 2 are active, you can only enchant at least Iron or better and need all Armor to be Iron or better

Does this looks better?

**Comment by gisellevonbingen** [comment]
Great, you are genius.

**Comment by gisellevonbingen** [comment]
ok, next version released.
https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/4251889

**Comment by Lgmrszd** [comment]
Looks great, thank you!

**Comment by gisellevonbingen** [comment]
Ok, thx for good idea
