### ISSUE TITLE
Space Breathing also act as Scuba (breathe underwater)

### ISSUE THREAD

**Issue by Lgmrszd** [gisellevonbingen/Minecraft-BossTools-Addon#136]
### The details

With full Space Suit on, you can breath underwater. Oxygen from Space Suit (chestplate piece) is consumed.

If you could also breath underwater with Space Breathing it would be cool.

**Comment by Lgmrszd** [comment]
Also, just a little suggestion, but maybe it's a good one:
Since it's related to breathing, recipes could be changed:
Space Breathing Enchantment -> Require "Respiration" book
Space Breathing Upgrade (PneumaticCraft) -> Require "SCUBA Upgrade"
I don't have Mekanism in my game for now but there's also SCUBA equipment in this mod that can be used in the upgrade.

I understand if this mod is supposed to be not hard to play so it's okay if you decide to keep current recipes. I can make a datapack for these recipes.

**Comment by gisellevonbingen** [comment]
Maybye that feature is not intended.
It is can't in overworld and glacio.
(https://github.com/MrScautHD/Beyond-Earth/blob/1.18.2/src/main/java/net/mrscauthd/beyond_earth/events/OxygenSystem.java#L17)


I think it is cool idea. `Need other enchanted book for crafting breathing echanted book`.
Maybe more better to need '`Fire Protection`'  for crafting `'Space Fire Proof'`.
And `'Father Falling'` be used to crafting `'Gravity Normalizing'`.
But I'll put it on hold for now, considering other enchantments that may be added later.

I'll think about the other recipe changes a little more.
i'm pursue to use Beyond Earth own items at crafting as possible.

They would be appropriate to make it as a data pack now.
