### ISSUE TITLE
Version 1.16.5-2.14 is marked for Fabric?

### ISSUE THREAD

**Issue by pavog** [gisellevonbingen/Minecraft-BossTools-Addon#142]
### Minecraft Version

1.16.5

### Forge Version

idk

### Space-BossTools or Beyond Earth Version

idk

### Addon Mod Version (This Mod)

1.16.5-2.14

### The details

Hi, I saw that version [1.16.5-2.14](https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/4251886) is available for Fabric but all other versions are available for Forge.
I guess this is a typo / misslick, right?!?

**Comment by gisellevonbingen** [comment]
Oh, It just missclick.
I didn't knew it.
tysm!
