### ISSUE TITLE
Implement Steel Management Config

### ISSUE THREAD

**Issue by Lgmrszd** [gisellevonbingen/Minecraft-BossTools-Addon#143]
### The details

I saw that you've implemented this for Beyond Earth already in this PR: https://github.com/MrScautHD/Beyond-Earth/pull/176
Unfortunately the 1.18.2 version on CurseForge is still old and doesn't include that.
Since this addon updates often I think it would be good if you added that option here (until Beyond Earth devs update their 1.18.2 version on CurseForge)

**Comment by gisellevonbingen** [comment]
That pull request is inappropriate as implementation at Addon.
Can you request update to Beyond Earth devs first?

Else.. If you can install CraftTweaker mod.
Can disable recipes via this script.

DisableSteel.zs
```zs
craftingTable.removeByName("beyond_earth:steel_ingot");
craftingTable.removeByName("beyond_earth:steel_ingot_from_nugget");
craftingTable.removeByName("beyond_earth:steel_block");
craftingTable.removeByName("beyond_earth:steel_nugget_from_ingot");

blastFurnace.removeByName("beyond_earth:steel_ingot_blasting");
```

**Comment by Lgmrszd** [comment]
Thanks, that would work
