### ISSUE TITLE
[1.18.1 Crash] Crash on render

### ISSUE THREAD

**Issue by itsdinkd** [gisellevonbingen/Minecraft-BossTools-Addon#16]
### Minecraft Version

1.18.1

### Forge Version

39.0.10

### Space-BossTools or Beyond Earth Version

5.9b

### Addon Mod Version (This Mod)
[crash log ](https://github.com/MrScautHD/Beyond-Earth/files/7820233/crash-2022-01-06_04.32.00-client.txt)
### The details

https://github.com/MrScautHD/Beyond-Earth/issues/26 

not my issue, reporting though so it does not get lost; and gets fixed.

**Comment by gisellevonbingen** [comment]
it will solved to update Beyond Earth to 1.18.1-5.9c
https://www.curseforge.com/minecraft/mc-mods/beyond-earth/files/3582260

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/149555402-9b805a56-55f0-4e67-a165-2e12866d9db3.png)

The user was already on 5.9c, you can see in the logs.

**Comment by gisellevonbingen** [comment]
ah, sry
require addon mod update to 1.18.1-1.2
https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/3581800
