### ISSUE TITLE
[1.18.1] rocket disappear unable to leave earth

### ISSUE THREAD

**Issue by DamianBerek** [gisellevonbingen/Minecraft-BossTools-Addon#17]
### Minecraft Version

1.18.1

### Forge Version

39.0.5

### Space-BossTools or Beyond Earth Version

1-6.0b

### Addon Mod Version (This Mod)

1.18.1-1.4

### The details

in server
launch rocket 
rocket despawns before reaching orbit player fell down every time.
works if i enable creative or in single player game but not on server

**Comment by gisellevonbingen** [comment]
it looks parent mod's problem
what use you server program?

**Comment by DamianBerek** [comment]
i use another quality modpack 3 on forge

**Comment by gisellevonbingen** [comment]
can i get that modpack url?

**Comment by DamianBerek** [comment]
https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-3

**Comment by gisellevonbingen** [comment]
thx, i will test
it may take a little while!

**Comment by DamianBerek** [comment]
not a problem i need a fix haha :D so take your time :)

**Comment by gisellevonbingen** [comment]
what did you click on server? (yellow, green border)
green : create space station, and teleport to orbit dimension
yellow : just go to orbit dimension, if you not create space station, fell down to earth
so other sentence, require green button first
![image](https://user-images.githubusercontent.com/44163945/149951942-19c9866f-c263-4f5f-9189-09f3751fc77c.png)

creative mode is always enable space station button
but survival mode is require ingredient items of space station

**Comment by DamianBerek** [comment]
i dont get that screen. rocket fly up to height limit then disapear and i am falling down

**Comment by gisellevonbingen** [comment]
I thought that problem was fixed
sry, nothing I can do for you
it need to fix it in Beyond Earth

**Comment by gisellevonbingen** [comment]
is BeyondEarth version 6.0b right?

**Comment by DamianBerek** [comment]
yes that ius correct ok thanks anyway
