### ISSUE TITLE
Beyond-Earth-Giselle-Addon loads JEI recipes slowly

### ISSUE THREAD

**Issue by mezz** [gisellevonbingen/Minecraft-BossTools-Addon#18]
### Minecraft Version

1.18.1

### Forge Version

39.0.43

### Space-BossTools or Beyond Earth Version

1.18.1-6.0b

### Addon Mod Version (This Mod)

1.18.1-1.4

### The details

Hello,

I am profiling a large mod pack (ATM 7) and I found that `beyond_earth_giselle_addon.common.compat.jer.AddonJeiPluginJer.registerRecipes`
takes a long time, about 25 seconds on my laptop. 
Most other JEI plugins in the pack load recipes in under 100 milliseconds.

All of the time is spent in 
`net.mrscauthd.beyond_earth.entity.alien.AlienEntity.<init>(EntityType, Level)`

I think if you can get the recipe information without initializing all of the entities, it will run much faster.

**Comment by gisellevonbingen** [comment]
oh, It's something I didn't care about at all.
i fixed initializing AlienEntity like you said
now, registerRecipes run as super faster

in my desktop, i measure taking time about 'registerRecipes' 
before : average 720 ms
after : average 40 ms

thx very much!!

**Comment by mezz** [comment]
Nice, thank you!
