### ISSUE TITLE
[1.16.5] Feature Request: Space Station item tags

### ISSUE THREAD

**Issue by Elfinlocks** [gisellevonbingen/Minecraft-BossTools-Addon#20]
### The details

In the current version of Boss Tools/Beyond Earth for 1.16.5, version 5.5e, you cannot use iron plates and steel ingots from other mods for space station construction, it only accepts specifically the ones from space boss tools. Can this please be fixed? Space Stations are literally unusable in modpacks right now due to this. The dev team of boss tools refuses to resolve this because 1.16 is an older version.

Any assistance is greatly appreciated, thank you.

**Comment by gisellevonbingen** [comment]
I'm trying backporting space station recipe feature from version 1.18.1,
And addon mod will modify some planet selection related code in Space-BossTools 1.16.5-5.5e

To recap changes, it is as follows:
1. Add Space Station Recipe using tag (you can modify it, but require same path)
1. Add Space Station JEI Category
1. Space Station Item Requirements use tag on recipe

Space Station Recipe File/Category
![image](https://user-images.githubusercontent.com/44163945/152930739-ae28ad23-bec7-49ff-b882-47da6fad679a.png)
![image](https://user-images.githubusercontent.com/44163945/152930750-930ca9c9-5586-4227-b141-8b33c3277f80.png)


Test result on my server (Mohist)
1. Steel Ingot from Mekanism, Immersive Engineering, Space-BossTools 
1. Iron Plate from Immersive Engineering, Space-BossTools, Thermal Series

![image](https://user-images.githubusercontent.com/44163945/152930759-6e24c08e-4348-4113-b51c-3f29bb25e24e.png)
![image](https://user-images.githubusercontent.com/44163945/152930762-16f2f836-de12-4ac4-8e64-e8e33bd5511b.png)
![image](https://user-images.githubusercontent.com/44163945/152930769-fea97950-3efe-4581-94f4-b5f4eebb3af8.png)

**Comment by Elfinlocks** [comment]
Thank you so much Giselle, you are the best!

**Comment by gisellevonbingen** [comment]
New version 1.16.5-1.12 released
Now under review from curseforge
