### ISSUE TITLE
Enchantments cannot be used

### ISSUE THREAD

**Issue by Vej-sys** [gisellevonbingen/Minecraft-BossTools-Addon#32]
### Minecraft Version

1.18.1

### Forge Version

39.0.66

### Space-BossTools or Beyond Earth Version

1.18.1-6.0d

### Addon Mod Version (This Mod)

1.18.1-1.7

#### Modpack: ATM7 0.2.37
**Reproduction**
Gamemode: survival
Steps: 
- Get a space breathing book
- try to use an anvil to add the enchantment to a diamond helmet
- done.

This extends to the other enchantments.
Additionally, it seems the modpack's enchantments don't appear when trying to enchant a gear piece ( ie: space breathing with helmet, gravity normalizing with boots ). However, they do appear with the 'Tome of the Others' from apotheosis..

  **Screenshot**
![image](https://user-images.githubusercontent.com/13587396/153758921-0b418471-095a-4563-9d9e-d280441cf1c3.png)

**Comment by gisellevonbingen** [comment]
Sry, all enchantments only enchant to item having energy storage
Vanilla armors not support yet
I'll add a tooltip to the enchanted book
