### ISSUE TITLE
You can remove the "== true" part

### ISSUE THREAD

**Issue by IStrikeboomI** [gisellevonbingen/Minecraft-BossTools-Addon#43]
### The details

https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/blob/7a2fce4c3402ab94383985a143dcc4b1ed211279/src/main/java/beyond_earth_giselle_addon/common/fluid/FluidUtil3.java#L21

**Comment by gisellevonbingen** [comment]
Thank you for your interest.
that code was intended

because i use condition == false instead of !condition
so, use to condition == true
