### ISSUE TITLE
[1.18.2] Beyond-Earth-1.18.2-6.1 changed the oxygen storage

### ISSUE THREAD

**Issue by Baggytrousers27** [gisellevonbingen/Minecraft-BossTools-Addon#73]
### Minecraft Version

1.18.2

### Forge Version

40.0.49

### Space-BossTools or Beyond Earth Version

Beyond-Earth-1.18.2-6.1

### Addon Mod Version (This Mod)

Beyond-Earth-Giselle-Addon-1.18.2-2.5

### The details

Startup error
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/mrscauthd/beyond_earth/capability/oxygen/IOxygenStorageHolder
Exit Code: -1

[Crashlog](https://pastebin.com/cuT6wSjw)

**Comment by gisellevonbingen** [comment]
oh, Beyond-Earth was updated?
i will check

**Comment by gisellevonbingen** [comment]
It fixed (https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/3751425)
Thanks report!

**Comment by Baggytrousers27** [comment]
¦D
