### ISSUE TITLE
Incompatible with JAOPCA

### ISSUE THREAD

**Issue by freopt** [gisellevonbingen/Minecraft-BossTools-Addon#76]
### Minecraft Version

1.18.2

### Forge Version

40.0.52

### Space-BossTools or Beyond Earth Version

6.1

### Addon Mod Version (This Mod)

2.6

### The details

Crashes when loading with JAOPCA
https://github.com/TheLMiffy1111/JAOPCA/issues/225#event-6441116088
[crash-2022-04-15_11.19.07-fml.txt](https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/files/8496949/crash-2022-04-15_11.19.07-fml.txt)

**Comment by gisellevonbingen** [comment]
Fix at https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/3754838
Thanks report!

**Comment by Xplodin** [comment]
this error came back

**Comment by gisellevonbingen** [comment]
> this error came back

Please create a new issue.
