### ISSUE TITLE
[1.16.5] the mod doesn't work with the new version

### ISSUE THREAD

**Issue by TainanRezende** [gisellevonbingen/Minecraft-BossTools-Addon#8]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Space-BossTools or Beyond Earth Version

1.16.5-5.5e

### Addon Mod Version (This Mod)

1.16.5-1.7

### The details

when I put the new version of the mod (I update it on my server) along with the new version of the mekanism the server n aber gives the following log

https://gist.github.com/TainanRezende/044e4fe9f0bcbf385d0d7e44b8000102

**Comment by gisellevonbingen** [comment]
i find it,
patch soon

--------
Can't reproduce
send me mod list or reproduce steps

**Comment by TainanRezende** [comment]
> i find it, patch soon
> 
> Can't reproduce send me mod list or reproduce steps

this is the modpack link (I created and updated) if you want to test, in the last update I updated the mods that had updated and due to a bug (NOTE: ON SERVER, RESOLUTION THE BUG IS ON SERVER) I did not update your mod and mekanism

NOTE: THE MODS ARE APPEARING WITH A PREVIOUS VERSION (OUTDATED) BECAUSE I'M PUTTING ONE BY ONE IN THE INICIO SERVER, IF IT STARTED RIGHT I DELIGO AND PUT ANOTHER SO THAT YOU CAN KNOW WHICH THE PROBLEM, IN TECHNIC, EVERYTHING IS UPDATED AND EVERYTHING IS UPDATED BUT YOURS UPDATED THE MECHANISM

https://www.technicpack.net/modpack/techmagic4litepowerbybr-thaus.1896433


Mod List: 
		CyclopsCore-1.16.5-1.12.1.jar                     |Cyclops Core                  |cyclopscore                   |1.12.1              |CREATE_REG|Manifest: NOSIGNATURE
		create-stuff-additions1.16.5_v1.1.5.jar           |Create Stuff Additions        |create_stuff_additions        |1.1.5               |CREATE_REG|Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |CREATE_REG|Manifest: NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |CREATE_REG|Manifest: NOSIGNATURE
		JAVD-2.6.1-build.48+mc1.16.5.jar                  |Just Another Void Dim         |javd                          |2.6.1-build.48+mc1.1|CREATE_REG|Manifest: NOSIGNATURE
		HammerLib-1.16.5-16.3.27.jar                      |HammerLib                     |hammerlib                     |16.3.27             |CREATE_REG|Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |CREATE_REG|Manifest: NOSIGNATURE
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |CREATE_REG|Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |CREATE_REG|Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |CREATE_REG|Manifest: NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.4.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.4               |CREATE_REG|Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.1.jar                          |Placebo                       |placebo                       |4.6.1               |CREATE_REG|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |CREATE_REG|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |CREATE_REG|Manifest: NOSIGNATURE
		mdecore-1.16.4-16.1.0.jar                         |MattDahEpic Core              |mdecore                       |16.1.0              |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		biomeidfixer-1.16.5-1.0.1.s5.jar                  |Biome Id Fixer by Desagas     |biomeidfixer                  |1.16.5-1.0.1.s5     |CREATE_REG|Manifest: NOSIGNATURE
		reliquary-1.16.5-1.3.5.1100.jar                   |Reliquary                     |xreliquary                    |1.16.5-1.3.5.1100   |CREATE_REG|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.13.6.450.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.13.6.450   |CREATE_REG|Manifest: NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |CREATE_REG|Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |CREATE_REG|Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.0.455.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.0              |CREATE_REG|Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |CREATE_REG|Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.21.jar                      |Carry On                      |carryon                       |1.15.5.21           |CREATE_REG|Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.133.jar         |Just Enough Resources         |jeresources                   |0.12.1.133          |CREATE_REG|Manifest: NOSIGNATURE
		XNetGases-1.16.5-2.3.8.jar                        |XNet Gases                    |xnetgases                     |2.3.8               |CREATE_REG|Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.16.5-1.3.1.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		Upgraded+Netherite+1.10.1.jar                     |Upgraded Netherite            |upgradednetherite             |1.10.1              |CREATE_REG|Manifest: NOSIGNATURE
		novillagerdm-1.0.1.jar                            |No Villager Death Messages    |novillagerdm                  |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		easy_piglins-1.16.5-1.0.2.jar                     |Easy Piglins                  |easy_piglins                  |1.16.5-1.0.2        |CREATE_REG|Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |CREATE_REG|Manifest: NOSIGNATURE
		alltheores-1.3.6-1.16.5-36.1.0.jar                |AllTheOres                    |alltheores                    |1.3.6-1.16.5-36.1.0 |CREATE_REG|Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |CREATE_REG|Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.7-16.jar       |Industrial Foregoing          |industrialforegoing           |3.2.14.7            |CREATE_REG|Manifest: NOSIGNATURE
		ExponentialPower-2.0.1.jar                        |Exponential Power             |exponentialpower              |2.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		torchmaster-2.3.8.jar                             |Torchmaster                   |torchmaster                   |2.3.8               |CREATE_REG|Manifest: NOSIGNATURE
		CommonCapabilities-1.16.5-2.8.0.jar               |CommonCapabilities            |commoncapabilities            |2.8.0               |CREATE_REG|Manifest: NOSIGNATURE
		fastfurnaceminusreplacement-1.1-1.16.3.jar        |Fast Furnace Minus Replacement|fastfurnaceminusreplacement   |1.1-1.16.3          |CREATE_REG|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.484-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.484   |CREATE_REG|Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.1.0.455.jar           |Mekanism: Additions           |mekanismadditions             |10.1.0              |CREATE_REG|Manifest: NOSIGNATURE
		valkyrielib-1.16.5-3.0.9.5.jar                    |ValkyrieLib                   |valkyrielib                   |1.16.5-3.0.9.5      |CREATE_REG|Manifest: NOSIGNATURE
		envirocore-1.16.5-3.0.9.3.jar                     |Environmental Core            |envirocore                    |1.16.5-3.0.9.3      |CREATE_REG|Manifest: NOSIGNATURE
		envirotech-1.16.5-3.0.9.4.jar                     |Environmental Tech            |envirotech                    |1.16.5-3.0.9.4      |CREATE_REG|Manifest: NOSIGNATURE
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               |CREATE_REG|Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |CREATE_REG|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.15-mc1.16.5.jar        |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.15              |CREATE_REG|Manifest: NOSIGNATURE
		Botania-1.16.5-420.1.jar                          |Botania                       |botania                       |1.16.5-420.1        |CREATE_REG|Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |CREATE_REG|Manifest: NOSIGNATURE
		spark-forge.jar                                   |spark                         |spark                         |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		SolarFluxReborn-1.16.5-16.3.9.jar                 |Solar Flux Reborn             |solarflux                     |16.3.9              |CREATE_REG|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.6.7.jar                   |Curios API                    |curios                        |1.16.5-4.0.6.7      |CREATE_REG|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |CREATE_REG|Manifest: NOSIGNATURE
		OreExcavation-1.8.157.jar                         |Ore Excavation                |oreexcavation                 |1.8.157             |CREATE_REG|Manifest: e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |CREATE_REG|Manifest: NOSIGNATURE
		malilib-forge-1.16.5-0.10.0-dev.21+beta.1.jar     |MaLiLib                       |malilib                       |0.10.0-dev.21+beta.1|CREATE_REG|Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |CREATE_REG|Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.0.455.jar               |Mekanism: Tools               |mekanismtools                 |10.1.0              |CREATE_REG|Manifest: NOSIGNATURE
		constructionwand-1.16.5-2.6.jar                   |Construction Wand             |constructionwand              |1.16.5-2.6          |CREATE_REG|Manifest: NOSIGNATURE
		architectury-1.26.43.jar                          |Architectury                  |architectury                  |1.26.43             |CREATE_REG|Manifest: NOSIGNATURE
		AI-Improvements-1.16.5-0.4.0.jar                  |AI-Improvements               |aiimprovements                |0.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		trashcans-1.0.11-mc1.16.jar                       |Trash Cans                    |trashcans                     |1.0.11              |CREATE_REG|Manifest: NOSIGNATURE
		chunkloaders-1.1.7-mc1.16.5.jar                   |Chunk Loaders                 |chunkloaders                  |1.1.7               |CREATE_REG|Manifest: NOSIGNATURE
		bwncr-1.16.5-3.10.16.jar                          |Bad Wither No Cookie Reloaded |bwncr                         |1.16.5-3.10.16      |CREATE_REG|Manifest: NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |CREATE_REG|Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.5.438-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.5.438           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |CREATE_REG|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.57.jar                  |GeckoLib                      |geckolib3                     |3.0.57              |CREATE_REG|Manifest: NOSIGNATURE
		Cyclic-1.16.5-1.5.12.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.12       |CREATE_REG|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		rhino-forge-1605.1.5-build.75.jar                 |Rhino                         |rhino                         |1605.1.5-build.75   |CREATE_REG|Manifest: NOSIGNATURE
		SimplyJetpacks2-1.16.5-2.6.11.2.jar               |Simply Jetpacks 2             |simplyjetpacks                |1.16.5-2.6.11.2     |CREATE_REG|Manifest: NOSIGNATURE
		Cucumber-1.16.5-4.1.12.jar                        |Cucumber Library              |cucumber                      |4.1.12              |CREATE_REG|Manifest: NOSIGNATURE
		bountifulbaubles-1.16.5-0.1.0-forge.jar           |Bountiful Baubles             |bountifulbaubles              |1.16.5-0.1.0        |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.138.jar                          |Just Enough Items             |jei                           |7.7.1.138           |CREATE_REG|Manifest: NOSIGNATURE
		kubejs-forge-1605.3.19-build.229.jar              |KubeJS                        |kubejs                        |1605.3.19-build.229 |CREATE_REG|Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.3.jar                    |AttributeFix                  |attributefix                  |10.1.3              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.1.jar                    |Environmental                 |environmental                 |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		goblintraders-1.6.0-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.0.455.jar                    |Mekanism                      |mekanism                      |10.1.0              |CREATE_REG|Manifest: NOSIGNATURE
		ae2extras-1.3.1-1.16.5.jar                        |AE2 Extras                    |ae2extras                     |1.3.1-1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		WAWLA-1.16.5-8.0.8.jar                            |WAWLA                         |wawla                         |8.0.8               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		RingsOfAscension-1.16.4-1.6.0.jar                 |Rings of Ascension            |ringsofascension              |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |CREATE_REG|Manifest: NOSIGNATURE
		Space-BossTools-1.16.5-5.5d.jar                   |Space-BossTools               |boss_tools                    |5.5                 |CREATE_REG|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |CREATE_REG|Manifest: NOSIGNATURE
		Clumps-6.0.0.27.jar                               |Clumps                        |clumps                        |6.0.0.27            |CREATE_REG|Manifest: NOSIGNATURE
		appliedenergistics2-8.4.5.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.5               |CREATE_REG|Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		lazierae2-1.16.5-1.1.4.jar                        |LazierAE2                     |lazierae2                     |1.1.4               |CREATE_REG|Manifest: NOSIGNATURE
		Artifacts-1.16.5-2.10.4.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.4       |CREATE_REG|Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.16.5-1.5.0.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.5.0        |CREATE_REG|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |CREATE_REG|Manifest: NOSIGNATURE
		BotanyPots-1.16.5-7.1.30.jar                      |BotanyPots                    |botanypots                    |7.1.30              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BotanyTrees-1.16.5-3.0.6.jar                      |BotanyTrees                   |botanytrees                   |3.0.6               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		DungeonCrawl-1.16.5-2.3.5.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.5               |CREATE_REG|Manifest: NOSIGNATURE
		pneumaticcraft-repressurized-1.16.5-2.14.6-277.jar|PneumaticCraft: Repressurized |pneumaticcraft                |1.16.5-2.14.6-277   |CREATE_REG|Manifest: NOSIGNATURE
		TravelAnchors-2.4.jar                             |Travel Anchors                |travel_anchors                |2.4                 |CREATE_REG|Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |CREATE_REG|Manifest: NOSIGNATURE
		TinyMobFarm-1.16.4-1.1.1.jar                      |Tiny Mob Farm                 |tinymobfarm                   |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		mcjtylib-1.16-5.1.2.jar                           |McJtyLib                      |mcjtylib                      |1.16-5.1.2          |CREATE_REG|Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.1.1.jar                        |RFToolsBase                   |rftoolsbase                   |1.16-2.1.1          |CREATE_REG|Manifest: NOSIGNATURE
		xnet-1.16-3.0.15.jar                              |XNet                          |xnet                          |1.16-3.0.15         |CREATE_REG|Manifest: NOSIGNATURE
		mahoutsukai-1.16.5-v1.33.6.jar                    |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.33.6      |CREATE_REG|Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		projecte-integration-1.16.5-4.2.0.jar             |ProjectE Integration          |projecteintegration           |4.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		EnderStorage-1.16.5-2.8.0.168-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.168           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		ImmersivePetroleum-1.16.5-3.3.0-10.jar            |Immersive Petroleum           |immersivepetroleum            |3.3.0-10            |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.7-27.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.7-27     |CREATE_REG|Manifest: NOSIGNATURE
		BrandonsCore-1.16.5-3.0.11.238-universal.jar      |Brandon's Core                |brandonscore                  |3.0.11.238          |CREATE_REG|Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		Draconic-Evolution-1.16.5-3.0.18.428-universal.jar|Draconic Evolution            |draconicevolution             |3.0.18.428          |CREATE_REG|Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		AutoRestart-1.16.5-2.0.0.jar                      |Auto Restart                  |auto_restart                  |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		MysticalAgriculture-1.16.5-4.2.6.jar              |Mystical Agriculture          |mysticalagriculture           |4.2.6               |CREATE_REG|Manifest: NOSIGNATURE
		MysticalAgradditions-1.16.5-4.2.4.jar             |Mystical Agradditions         |mysticalagradditions          |4.2.4               |CREATE_REG|Manifest: NOSIGNATURE
		CraftingTweaks_1.16.5-12.2.1.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.1              |CREATE_REG|Manifest: NOSIGNATURE
		ZeroCore2-1.16.5-2.1.9.jar                        |Zero CORE 2                   |zerocore                      |1.16.5-2.1.9        |CREATE_REG|Manifest: NOSIGNATURE
		ExtremeReactors2-1.16.5-2.0.34.jar                |Extreme Reactors              |bigreactors                   |1.16.5-2.0.34       |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.4.0.6.jar                      |CoFH Core                     |cofh_core                     |1.4.0.6             |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.16.5-1.4.1.7.jar             |Thermal Series                |thermal                       |1.4.1.7             |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.16.5-1.4.1.3.jar              |Thermal Expansion             |thermal_expansion             |1.4.1.3             |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_locomotion-1.16.5-1.4.1.2.jar             |Thermal Locomotion            |thermal_locomotion            |1.4.1.2             |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		TConstruct-1.16.5-3.3.1.316.jar                   |Tinkers' Construct            |tconstruct                    |3.3.1.316           |CREATE_REG|Manifest: NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |CREATE_REG|Manifest: NOSIGNATURE
		logprot-1.16-1.5.jar                              |Logprot                       |logprot                       |1.4                 |CREATE_REG|Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.18.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.18              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.7-22.jar                    |Titanium                      |titanium                      |3.2.8.7             |CREATE_REG|Manifest: NOSIGNATURE
		mana-and-artifice-1.5.1.5.jar                     |Mana and Artifice             |mana-and-artifice             |1.5.1.5             |CREATE_REG|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.7-143.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.7-143    |CREATE_REG|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		EntityCulling-1.16.5-2.1.6.jar                    |Entity Culling                |entity_culling                |2.1.6               |CREATE_REG|Manifest: NOSIGNATURE
		EmendatusEnigmatica-1.2.15-build.7+mc1.16.5.jar   |Emendatus Enigmatica          |emendatusenigmatica           |1.16.5-1.2.15       |CREATE_REG|Manifest: NOSIGNATURE
		ftb-industrial-contraptions-1605.1.3-build.103.jar|FTB Industrial Contraptions   |ftbic                         |1605.1.3-build.103  |CREATE_REG|Manifest: NOSIGNATURE
		Numina-1.16.5-2.1.14.jar                          |Numina                        |numina                        |2.1.14              |CREATE_REG|Manifest: NOSIGNATURE
		ModularPowersuits-1.16.5-2.1.18.jar               |MachineMuse's Modular Powersui|powersuits                    |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		turtlemancy-1.16.5-1.6.3.jar                      |Turtlemancy                   |turtlemancy                   |1.6.3               |CREATE_REG|Manifest: NOSIGNATURE
		Krate-1.16.5-0.1.4.jar                            |Krate                         |krate                         |0.1.4               |CREATE_REG|Manifest: NOSIGNATURE
		rftoolsbuilder-1.16-3.1.4.jar                     |RFToolsBuilder                |rftoolsbuilder                |1.16-3.1.4          |CREATE_REG|Manifest: NOSIGNATURE
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |CREATE_REG|Manifest: NOSIGNATURE
		easy_villagers-1.16.5-1.0.11.jar                  |Easy Villagers                |easy_villagers                |1.16.5-1.0.11       |CREATE_REG|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |CREATE_REG|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |CREATE_REG|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.147.jar                         |Mantle                        |mantle                        |1.6.147             |CREATE_REG|Manifest: NOSIGNATURE
		JAOPCA-1.16.5-3.4.2.21.jar                        |JAOPCA                        |jaopca                        |3.4.2.21            |CREATE_REG|Manifest: NOSIGNATURE
		itemcollectors-1.1.3-mc1.16.jar                   |Item Collectors               |itemcollectors                |1.1.3               |CREATE_REG|Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.7.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.7        |CREATE_REG|Manifest: NOSIGNATURE
		myrtrees-forge-1.0.19.jar                         |Myrtrees                      |myrtrees                      |1.0.19              |CREATE_REG|Manifest: NOSIGNATURE
		FastWorkbench-1.16.5-4.6.1.jar                    |Fast Workbench                |fastbench                     |4.6.1               |CREATE_REG|Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.37.jar                   |Polymorph                     |polymorph                     |1.16.5-0.37         |CREATE_REG|Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |CREATE_REG|Manifest: NOSIGNATURE
		Quark-r2.4-321.jar                                |Quark                         |quark                         |r2.4-321            |CREATE_REG|Manifest: NOSIGNATURE
		materialis-1.16.5-2.4.1.jar                       |Materialis                    |materialis                    |1.16.5-2.4.1        |CREATE_REG|Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.4.0.jar                   |Storage Drawers               |storagedrawers                |8.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		FluxNetworks-1.16.5-6.1.7.12.jar                  |Flux Networks                 |fluxnetworks                  |6.1.7.12            |CREATE_REG|Manifest: NOSIGNATURE
		performant-1.16.2-5-3.80m.jar                     |Performant                    |performant                    |3.73m               |CREATE_REG|Manifest: NOSIGNATURE
		norecipeadvancements-1.0.1.jar                    |No Recipe Advancements        |norecipeadvancements          |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		Space-BossTools_Giselle_Addon-1.16.5-1.5.jar      |Space-BossTools: Giselle Addon|boss_tools_giselle_addon      |1.5                 |ERROR     |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |CREATE_REG|Manifest: NOSIGNATURE
		ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.0               |CREATE_REG|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Chisel-MC1.16.5-2.0.1-alpha.4.jar                 |Chisel                        |chisel                        |MC1.16.5-2.0.1-alpha|CREATE_REG|Manifest: NOSIGNATURE
		occultism-1.16.5-1.23.6.jar                       |Occultism                     |occultism                     |1.16.5-1.23.6       |CREATE_REG|Manifest: NOSIGNATURE
		kubejs-immersive-engineering-1605.1.1-build.2.jar |KubeJS Immersive Engineering  |kubejs_immersive_engineering  |1605.1.1-build.2    |CREATE_REG|Manifest: NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		createaddition-1.16.5-20211215b.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20211215b    |CREATE_REG|Manifest: NOSIGNATURE

**Comment by gisellevonbingen** [comment]
ok maybe i fix b31084b3c2aa75dc5c2dee31843924ef2a73fa5a
try check out
https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/3581789

**Comment by TainanRezende** [comment]
> ok maybe i fix [b31084b](https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/commit/b31084b3c2aa75dc5c2dee31843924ef2a73fa5a) try check out https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/3581789

it worked the server started normally
